#!/usr/bin/env bash

export DOTFILES=$HOME/.dotfiles
export HOMEBREW_PREFIX="$(brew --prefix 2>/dev/null)"

# rbenv
export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"

# personal paths
export CDPATH=".:$HOME:$HOME/src"
export PATH="./bin:$PATH:$DOTFILES/bin"

# Default editor
export EDITOR='vim'
# improve ls colors
export CLICOLOR=1
# mysql prompt
export MYSQL_PS1='\d\$ '
# my lang
export LC_ALL="en_US.UTF-8"
export LC_CTYPE="en_US.UTF-8"
export LANG="en_US.UTF-8"

source $DOTFILES/lib/heroku
source $DOTFILES/lib/aliases
source $DOTFILES/lib/git
source $DOTFILES/lib/less

__build_prompt() {
  local last_status=$?
  local blue='\[\e[0;34m\]'
  local red='\[\e[0;31m\]'
  local green='\[\e[0;32m\]'
  local reset='\[\e[00m\]'

  if [[ $last_status = 0 ]]
  then
    local prompt_color=$green
  else
    local prompt_color=$red
  fi

  __git_ps1 "$blue\w$reset" "\\n$prompt_color\$$reset "
};
export PROMPT_COMMAND=__build_prompt

# Autocomplete
load_bash_completion() {
  local prefix=${HOMEBREW_PREFIX:-/usr/local}
  local brew_bash_completion="$prefix/etc/bash_completion"

  if [ -e $brew_bash_completion ]
  then
    source $brew_bash_completion
    source "$prefix/Library/Contributions/brew_bash_completion.sh"
  else
    source "/etc/bash_completion"
  fi
}; load_bash_completion

# Make ** works beautiful, works to any nested directory.
shopt -s globstar
# Enable dot files/folder on autocomplete
shopt -s dotglob

bind "set completion-ignore-case on"
bind "set show-all-if-ambiguous on"
complete -A hostname   rsh rcp telnet rlogin r ftp ping disk
complete -A export     printenv
complete -A variable   export local readonly unset
complete -A enabled    builtin
complete -A alias      alias unalias
complete -A function   function
complete -A user       su mail finger
complete -o default -o nospace -F _rakecomplete rake
complete -o default -o nospace -F _capcomplete cap
complete -o default -o nospace -F _thorcomplete thor

# Append user history
shopt -s histappend

# History
export HISTCONTROL=$HISTCONTROL${HISTCONTROL+,}ignoredups
export HISTCONTROL=ignoreboth
export HISTFILESIZE=10000000000
export HISTSIZE=1000000

# Make ctrl-s works to incremental search, like ctrl-r to reverse
stty -ixon

# local env
if [ -e "$HOME/.env" ]
then
  source $HOME/.env
fi
