export DOTFILES=$HOME/.dotfiles

__build_prompt() {
  local last_status=$?
  local blue='\[\e[0;34m\]'
  local red='\[\e[0;31m\]'
  local green='\[\e[0;32m\]'
  local reset='\[\e[00m\]'

  if [[ $last_status = 0 ]]
  then
    local prompt_color=$green
  else
    local prompt_color=$red
  fi

  __git_ps1 "$blue\w $reset" "
$prompt_color\$$reset " "(%s)"
};

# Autocomplete
load_bash_completion() {
  local brew_prefix="`which brew --prefix 2>/dev/null`"
  local prefix=${brew_prefix:-/usr/local}

  source "/etc/bash_completion" 2>/dev/null
  source "$prefix/etc/bash_completion" 2>/dev/null
  source "$prefix/Library/Contributions/brew_bash_completion.sh" 2>/dev/null
}; load_bash_completion

# Make ** works beautiful, works to any nested directory.
shopt -s globstar

# Append user history
shopt -s histappend

bind "set completion-ignore-case on"
complete -A hostname   rsh rcp telnet rlogin r ftp ping disk
complete -A export     printenv
complete -A variable   export local readonly unset
complete -A enabled    builtin
complete -A alias      alias unalias
complete -A function   function
complete -A user       su mail finger
complete -o default -o nospace -F _rakecomplete rake
complete -o default -o nospace -F _capcomplete cap
complete -o default -o nospace -F _thorcomplete thor

# History
export HISTCONTROL=$HISTCONTROL${HISTCONTROL+,}ignoredups
export HISTCONTROL=ignoreboth
export HISTFILESIZE=10000000000
export HISTSIZE=1000000

export PROMPT_COMMAND=__build_prompt

source $DOTFILES/lib/my_env

# vim:ft=sh:
