# Fix PATH
if [ -x /usr/libexec/path_helper ]
then
  PATH=""
  eval `/usr/libexec/path_helper -s`
fi

export DOTFILES=$HOME/.dotfiles
export HOMEBREW_PREFIX="$(brew --prefix 2>/dev/null)"

# rbenv
export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"

# personal paths
export PATH="./bin:$DOTFILES/bin:$PATH"
export CDPATH=".:$HOME:$HOME/.config:$HOME/src"
for project in $(find ~/src/private -type d -depth 1 2>/dev/null); do
  export CDPATH="$CDPATH:$project"
done
export CDPATH="$CDPATH:~/src/private"

# Default editor
export EDITOR="nvim"
# improve ls colors
export CLICOLOR=1
# mysql prompt
export MYSQL_PS1='\d\$ '
# my lang
export LC_ALL="en_US.UTF-8"
export LC_CTYPE="en_US.UTF-8"
export LANG="en_US.UTF-8"

source $DOTFILES/lib/heroku
source $DOTFILES/lib/aliases
source $DOTFILES/lib/less
source $DOTFILES/lib/spectrum.zsh

source "$(brew --prefix)/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"

autoload -Uz compinit
compinit -C
autoload bashcompinit
bashcompinit
source "$(brew --prefix)/etc/bash_completion.d/git-prompt.sh"

export GIT_PS1_SHOWDIRTYSTATE=true
export GIT_PS1_SHOWSTASHSTATE=true
export GIT_PS1_SHOWUNTRACKEDFILES=true
export GIT_PS1_SHOWCOLORHINTS=true
export GIT_PS1_DESCRIBE_STYLE=branch
export GIT_PS1_SHOWUPSTREAM=verbose

__build_prompt() {
  if [[ $? = 0 ]]
  then
    local prompt_color="002"
  else
    local prompt_color="001"
  fi

  __git_ps1 "$FG[004]%~%f" "
$FG[$prompt_color]$%f %{$FX[reset]%}"
};
precmd_functions=(__build_prompt)

## Binds
# Use emacs key bindings
bindkey -e

# Del
bindkey '\e[3~'   delete-char

# c-x c-e edit command line in $EDITOR
autoload -U edit-command-line
zle -N edit-command-line
bindkey '\C-x\C-e' edit-command-line

## Completions
fpath=(/usr/local/share/zsh-completions $fpath)
brew_completion="${HOMEBREW_PREFIX:-/usr/local}/Library/Contributions/brew_zsh_completion.sh"
if [[ -e $brew_completion ]]
then
  source $brew_completion
fi

# Fix the \eb \ef and others.
export WORDCHARS=''

# colors on autocomplete
zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}

# case-insensitive (all),partial-word and then substring completion
zstyle ':completion:*' matcher-list \
  'm:{a-zA-Z}={A-Za-z}' \
  'r:|[._-]=* r:|=*' 'l:|=* r:|=*'

unsetopt menu_complete   # do not autoselect the first completion entry
unsetopt flowcontrol
setopt auto_menu         # show completion menu on succesive tab press
setopt complete_in_word
setopt always_to_end
skip_global_compinit=1

for key in '!' '$' '@' '/'; do
  bindkey "\e$key" _bash_complete-word
  bindkey "^X$key" _bash_list-choices
done

# do not correct me!!
unsetopt correct_all
unsetopt correct

## History
export HISTFILE=$HOME/.zhistory
export HISTSIZE=120000
export SAVEHIST=100000
setopt BANG_HIST                 # Treat the '!' character specially during expansion.
setopt INC_APPEND_HISTORY        # Write to the history file immediately, not when the shell exits.
setopt SHARE_HISTORY             # Share history between all sessions.
setopt HIST_SAVE_NO_DUPS         # Don't write duplicate entries in the history file.
setopt HIST_FIND_NO_DUPS         # Do not display a line previously found.
setopt HIST_IGNORE_ALL_DUPS      # Delete old recorded entry if new entry is a duplicate.
setopt HIST_IGNORE_DUPS          # Don't record an entry that was just recorded again.
setopt HIST_EXPIRE_DUPS_FIRST    # Expire duplicate entries first when trimming history.
setopt HIST_REDUCE_BLANKS        # Remove superfluous blanks before recording entry.
setopt HIST_VERIFY               # Don't execute immediately upon history expansion.
setopt HIST_NO_STORE             # Don't save history command on history
unsetopt HIST_IGNORE_SPACE       # Ignore space prefixed commands
unsetopt EXTENDED_HISTORY

## Extra
# easy regexp on list files (**)
setopt extendedglob
# include dotfiles in globbing
setopt glob_dots
# don't blow up with comments
setopt interactive_comments

# local env
if [ -e "$HOME/.env" ]
then
  source $HOME/.env
fi

# vim:ft=zsh:
