#!/usr/bin/env bash

# Enable full keyboard access for all controls (e.g. enable Tab in modal dialogs)
defaults write -g AppleKeyboardUIMode -int 3
# Turn on key repeat (Disable hold modifier)
defaults write -g ApplePressAndHoldEnabled -int 0
defaults write NSGlobalDomain InitialKeyRepeat -int 15
defaults write NSGlobalDomain KeyRepeat -int 0.02
# Enable auto replacement
defaults write -g WebAutomaticTextReplacementEnabled -int 1
# Disable auto-correct
defaults write NSGlobalDomain NSAutomaticSpellingCorrectionEnabled -int 0

# Layout
defaults write -g com.apple.HIToolbox '{
  AppleCurrentKeyboardLayoutInputSourceID = "com.apple.keylayout.US";
  AppleEnabledInputSources = ();
  AppleInputSourceHistory = ();
  AppleSelectedInputSources = ();
}'

# Custom shortcuts

# Safari
# * "Close Tab" = cmd-w (always)
defaults write com.apple.Safari NSUserKeyEquivalents '{
  "Close Tab" = "@w";
}'

# Finder
# * "Merge All Windows" - cmd-opt-ctrl-m
defaults write com.apple.Finder NSUserKeyEquivalents '{
  "Merge All Windows" = "@~^m";
}'

# Notes
# * Hide/Show Folders (sidebar) - cmd-shift-s
defaults write com.apple.Notes NSUserKeyEquivalents '{
    "Hide Folders" = "@$s";
    "Show Folders" = "@$s";
}'

# Preview
# * "Adjust Size..." - cmd-opt-ctrl-i
# * "Export" - cmd-opt-e
defaults write com.apple.Preview NSUserKeyEquivalents '{
  "Adjust Size..." = "@~^i";
  "Export..." = "@~e";
}'

# Keynote
# * "Rehearse Slideshow" - cmd-opt-x
defaults write com.apple.iWork.Keynote NSUserKeyEquivalents '{
  "Rehearse Slideshow" = "@~x";
}'

# VLC
# * "Float on Top" - cmd-opt-o
defaults write org.videolan.vlc NSUserKeyEquivalents '{
  "Float on Top" = "@~o";
}'

# WhatsApp
# * "Archive Chat" - cmd-shift-e
defaults write Whatsapp NSUserKeyEquivalents '{
  "Archive Chat" = "@$e";
}'

# Force global keyboard config to follow the 'local'
sudo cp ~/Library/Preferences/com.apple.HIToolbox.plist \
  /Library/Preferences/com.apple.HIToolbox.plist
