### Taps
tap homebrew/dupes
tap homebrew/versions
tap mitchty/entr
tap phinze/cask
### Apps
install ack
install apple-gcc42
install autoconf
install automake
install bash
install bash-completion
install brew-cask
install cscope
install ctags
install entr
install erlang-r16
install faac
install fcgi
install ffmpeg
install freetype
install gdbm
install gifsicle
install git
install go
install graphviz
install imagemagick
install imagesnap
install jpeg
install lame
install libevent
install libpng
install libtool
install libxml2
install macvim
install markdown
install mercurial
install mysql
install node
install openssl
install ossp-uuid
install pcre
install phantomjs
install pkg-config
install postgresql
install python
install readline
install reattach-to-user-namespace
install redis
install rename
install scala
install sqlite
install texi2html
install tmux
install tree
install vim --HEAD
install watch
install wget
install x264
install xvid
install yasm
install youtube-dl
install zsh
### Verify
doctor
