#!/usr/bin/env zsh

export DOTFILES="${HOME}/.dotfiles"

PATH="/usr/bin:/bin:/usr/sbin:/sbin" # system base PATH
PATH="${PATH}:/usr/local/bin"        # intel homebrew
PATH="${PATH}:/opt/homebrew/bin"     # M1 homebrew
PATH="${PATH}:${DOTFILES}/bin"       # my stuff
export PATH

mkdir -p "${HOME}/src"

"${DOTFILES}/installers/setup-macos" &&
"${DOTFILES}/installers/config" &&
"${DOTFILES}/installers/hosts" &&
"${DOTFILES}/installers/brew" &&
"${DOTFILES}/installers/nvim-nightly" &&
"${DOTFILES}/installers/repos_sync" &&
"${DOTFILES}/installers/others" &&
"${DOTFILES}/bin/upgrade"
