#!/usr/bin/env zsh

export DOTFILES="${HOME}/.dotfiles"

PATH="/usr/bin:/bin:/usr/sbin:/sbin" # system base PATH
PATH="${PATH}:/usr/local/bin" # intel homebrew
PATH="${PATH}:/opt/homebrew/bin" # M1 homebrew
export PATH

"${DOTFILES}/installers/kitty-install"
"${DOTFILES}/installers/setup-macos"
"${DOTFILES}/installers/stow"
"${DOTFILES}/installers/brew"

echo "> Basic softwares installed"
echo "> Run upgrade now"
