#!/bin/bash

cd $HOME

link_files() {
  local file_path="$HOME/.dotfiles"

  for f in \
    bashrc zshrc zshenv gitignore \
    gitconfig irbrc gemrc hushlogin \
    profile tmux.conf ctags ackrc
  do
    ln -sf "$file_path/$f" $HOME/.$f
  done
}; link_files

if [[ -e "$HOME/.zshrc" ]]
then
  source $HOME/.zshrc &>/dev/null
fi

if [[ ! -d "$HOME/.rbenv" ]]
then
  cd $HOME
  git clone git://github.com/sstephenson/rbenv.git .rbenv

  mkdir -p $HOME/.rbenv/plugins
  cd $HOME/.rbenv/plugins
  git clone git://github.com/sstephenson/ruby-build.git
fi

if [[ -e "/etc/zshenv" ]]
then
  sudo mv /etc/{zshenv,zshrc}
fi

# load/update git-prompt.sh
curl \
  https://raw.githubusercontent.com/git/git/master/contrib/completion/git-prompt.sh \
  > $HOME/.dotfiles/lib/git-prompt.sh

cd $HOME
