# vim:ft=zsh:

autoload -Uz compinit && compinit -C
autoload -Uz bashcompinit && bashcompinit
autoload -Uz colors && colors

export DOTFILES="${HOME}/.dotfiles"
export HOMEBREW_PREFIX="$(brew --prefix 2>/dev/null)"

export PATH="/usr/bin:/bin:/usr/sbin:/sbin"
export PATH="${HOMEBREW_PREFIX}/bin:${HOMEBREW_PREFIX}/sbin:${PATH}"
export PATH="${DOTFILES}/bin:./bin:${PATH}"

export HISTFILE=${HOME}/.zhistory
export HISTSIZE=120000
export SAVEHIST=100000

export PROMPT_EOL_MARK="" # Remove % from partial lines
export WORDCHARS="" # Fix the \eb \ef and others.

export HOMEBREW_NO_ANALYTICS=1

export EDITOR="nvim"

export GIT_PS1_SHOWDIRTYSTATE=true
export GIT_PS1_SHOWSTASHSTATE=true
export GIT_PS1_SHOWUNTRACKEDFILES=true
export GIT_PS1_SHOWCOLORHINTS=true
export GIT_PS1_DESCRIBE_STYLE=branch
export GIT_PS1_SHOWUPSTREAM=verbose

export GPG_TTY=$(tty)

zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=*' 'l:|=* r:|=*'
zstyle ':completion:::::' completer _expand _complete _ignored _approximate # enable approximate matches for completion

setopt always_to_end # move cursor to end if word had one match
setopt auto_menu # automatically use menu completion
setopt bang_hist # treat the '!' character specially during expansion.
setopt complete_in_word
setopt hist_expire_dups_first # expire duplicate entries first when trimming history.
setopt hist_find_no_dups # do not display a line previously found.
setopt hist_ignore_all_dups # delete old recorded entry if new entry is a duplicate.
setopt hist_ignore_dups # don't record an entry that was just recorded again.
setopt hist_no_store # don't save history command on history
setopt hist_reduce_blanks # remove superfluous blanks before recording entry.
setopt hist_save_no_dups # don't write duplicate entries in the history file.
setopt hist_verify # don't execute immediately upon history expansion.
setopt inc_append_history # write to the history file immediately, not when the shell exits.
setopt prompt_cr # remove % from partial lines
setopt prompt_sp # remove % from partial lines
setopt share_history # share history between all sessions.
unsetopt correct # do not correct me
unsetopt correct_all # do not correct me
unsetopt extended_history
unsetopt flowcontrol
unsetopt hist_ignore_space # ignore space prefixed commands
unsetopt menu_complete # do not navigate completion with arrows

tabs -2
skip_global_compinit=1
fpath=(${HOMEBREW_PREFIX}/share/zsh-completions ${fpath})
CDPATH=".:${HOME}:${HOME}/.config:${HOME}/src"

for key in '!' '$' '@' '/'; do
  bindkey "\e${key}" _bash_complete-word
  bindkey "^X${key}" _bash_list-choices
done

# To be overwritten on $HOME/.dotfiles.private/env
__ps1_extra() { echo ''; }

__ps1() {
  if [ "$?" -eq 0 ]
  then
    local prompt_color="%F{green}"
  else
    local prompt_color="%F{red}"
  fi

  local part1="%F{blue}%~%f"
  local part2=$(echo -e "\n${prompt_color}$%f ")
  local part3="$(print -P " %F{yellow}(%f%%s%F{yellow})$(__ps1_extra)")"

  __git_ps1 ${part1} ${part2} ${part3}
}
__rprompt() {
  if [ -d ".git" ]
  then
    local head="$(git symbolic-ref -q HEAD)"
    export RPROMPT="%F{008}$(git for-each-ref --format='%(upstream:short)' "${head}")%f"
  else
    export RPROMPT=""
  fi
}
precmd_functions=(__ps1 __rprompt)

source "${HOMEBREW_PREFIX}/opt/fzf/shell/completion.zsh" 2> /dev/null
source "${HOMEBREW_PREFIX}/opt/fzf/shell/key-bindings.zsh" 2> /dev/null
source "${HOMEBREW_PREFIX}/etc/bash_completion.d/git-prompt.sh"
source "${HOMEBREW_PREFIX}/opt/asdf/asdf.sh"
source "${HOMEBREW_PREFIX}/opt/asdf/etc/bash_completion.d/asdf.bash"
source "${HOMEBREW_PREFIX}/share/zsh-autosuggestions/zsh-autosuggestions.zsh"
source "${HOMEBREW_PREFIX}/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"

source "${DOTFILES}/lib/alias"
source "${DOTFILES}/lib/rails"
source "${HOME}/.dotfiles.private/env" # Private stuff
source "${HOME}/.env" 2>/dev/null # Ephemeral stuff
