#!/usr/bin/env bash

export DOTFILES=$HOME/.dotfiles
source "$DOTFILES/lib/env"

source "$(brew --prefix)/etc/bash_completion"

__build_prompt() {
  local last_status=$?
  local blue='\[\e[0;34m\]'
  local red='\[\e[0;31m\]'
  local green='\[\e[0;32m\]'
  local reset='\[\e[00m\]'

  if [[ $last_status = 0 ]]
  then
    local prompt_color=$green
  else
    local prompt_color=$red
  fi

  __git_ps1 "$blue\w$reset" "\\n$prompt_color\$$reset "
};
export PROMPT_COMMAND=__build_prompt

# Autocomplete
load_bash_completion() {
  local prefix=${HOMEBREW_PREFIX:-/usr/local}
  local brew_bash_completion="$prefix/etc/bash_completion"

  if [ -e $brew_bash_completion ]
  then
    source $brew_bash_completion
    source "$prefix/Library/Contributions/brew_bash_completion.sh"
  else
    source "/etc/bash_completion"
  fi
}; load_bash_completion

# Make ** works beautiful, works to any nested directory.
shopt -s globstar
# Enable dot files/folder on autocomplete
shopt -s dotglob

bind "set completion-ignore-case on"
bind "set show-all-if-ambiguous on"
complete -A hostname   rsh rcp telnet rlogin r ftp ping disk
complete -A export     printenv
complete -A variable   export local readonly unset
complete -A enabled    builtin
complete -A alias      alias unalias
complete -A function   function
complete -A user       su mail finger
complete -o default -o nospace -F _rakecomplete rake
complete -o default -o nospace -F _capcomplete cap
complete -o default -o nospace -F _thorcomplete thor

# Append user history
shopt -s histappend

# History
export HISTCONTROL=$HISTCONTROL${HISTCONTROL+,}ignoredups
export HISTCONTROL=ignoreboth
export HISTFILESIZE=10000000000
export HISTSIZE=1000000

# Make ctrl-s works to incremental search, like ctrl-r to reverse
stty -ixon
