#!/usr/bin/env zsh

# Fix PATH
if [ -x /usr/libexec/path_helper ]
then
  PATH=""
  eval `/usr/libexec/path_helper -s`
fi

export DOTFILES=$HOME/.dotfiles

source $DOTFILES/lib/spectrum.zsh

source "$(brew --prefix)/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"

autoload -Uz compinit
compinit -C
autoload bashcompinit
bashcompinit
source "$(brew --prefix)/etc/bash_completion.d/git-prompt.sh"

prompt_cmd() {
  local last_status=$?
  local blue="$FG[004]"
  local red="$FG[001]"
  local green="$FG[002]"
  local reset="$FX[reset]"

  if [[ $last_status = 0 ]]
  then
    local prompt_color=$green
  else
    local prompt_color=$red
  fi

  __git_ps1 "$blue%~%f" "
$prompt_color$%f %{$reset%}"
}
precmd_functions=(prompt_cmd) # zsh

## Binds
# Use emacs key bindings
bindkey -e

# Del
bindkey '\e[3~'   delete-char

# c-x c-e edit command line in $EDITOR
autoload -U edit-command-line
zle -N edit-command-line
bindkey '\C-x\C-e' edit-command-line

## Completions
fpath=(/usr/local/share/zsh-completions $fpath)
brew_completion="${HOMEBREW_PREFIX:-/usr/local}/Library/Contributions/brew_zsh_completion.sh"
if [[ -e $brew_completion ]]
then
  source $brew_completion
fi

# Fix the \eb \ef and others.
export WORDCHARS=''

# colors on autocomplete
zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}

# case-insensitive (all),partial-word and then substring completion
zstyle ':completion:*' matcher-list \
  'm:{a-zA-Z}={A-Za-z}' \
  'r:|[._-]=* r:|=*' 'l:|=* r:|=*'

unsetopt menu_complete   # do not autoselect the first completion entry
unsetopt flowcontrol
setopt auto_menu         # show completion menu on succesive tab press
setopt complete_in_word
setopt always_to_end
skip_global_compinit=1

for key in '!' '$' '@' '/'; do
  bindkey "\e$key" _bash_complete-word
  bindkey "^X$key" _bash_list-choices
done

# do not correct me!!
unsetopt correct_all
unsetopt correct

## History
export HISTFILE=$HOME/.zhistory
export HISTSIZE=120000
export SAVEHIST=100000
setopt BANG_HIST                 # Treat the '!' character specially during expansion.
setopt INC_APPEND_HISTORY        # Write to the history file immediately, not when the shell exits.
setopt SHARE_HISTORY             # Share history between all sessions.
setopt HIST_SAVE_NO_DUPS         # Don't write duplicate entries in the history file.
setopt HIST_FIND_NO_DUPS         # Do not display a line previously found.
setopt HIST_IGNORE_ALL_DUPS      # Delete old recorded entry if new entry is a duplicate.
setopt HIST_IGNORE_DUPS          # Don't record an entry that was just recorded again.
setopt HIST_EXPIRE_DUPS_FIRST    # Expire duplicate entries first when trimming history.
setopt HIST_REDUCE_BLANKS        # Remove superfluous blanks before recording entry.
setopt HIST_VERIFY               # Don't execute immediately upon history expansion.
setopt HIST_NO_STORE             # Don't save history command on history
unsetopt HIST_IGNORE_SPACE       # Ignore space prefixed commands
unsetopt EXTENDED_HISTORY

## Extra
# easy regexp on list files (**)
setopt extendedglob
# include dotfiles in globbing
setopt glob_dots
# don't blow up with comments
setopt interactive_comments

# Load zsh
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# My env customization (this line must be the very last on this file)
source "$DOTFILES/lib/env"
