export DOTFILES="${HOME}/.DOTFILES"

export XDG_BIN_HOME="${DOTFILES}/bin"
export XDG_CACHE_HOME="${HOME}/.cache"
export XDG_CONFIG_HOME="${HOME}/.config"
export XDG_DATA_HOME="${HOME}/.local/share"
export XDG_STATE_HOME="${HOME}/.local/state"

source "${XDG_CONFIG_HOME}/zsh/config"
