#!/usr/bin/env zsh

install_path="${XDG_CONFIG_HOME}/antidote"
list_path="${ZSH_CONFIG_HOME}/plugins/list"
loader_path="${ZSH_CONFIG_HOME}/plugins/loader"

if [[ ! "${install_path}/antidote.zsh" -nt "${list_path}" ]]; then
  [[ -e "${install_path}" ]] ||
    git clone --depth=1 https://github.com/mattmc3/antidote.git "${install_path}"

  (
    source "${install_path}/antidote.zsh"
    antidote bundle < "${list_path}" > "${loader_path}"
  )
fi

source "${loader_path}"
