#!/usr/bin/env zsh

function last_parts() {
  IFS="/" read -A parts <<< "$1"

  printf ".../%s/%s" "${parts[-2]}" "${parts[-1]}"
}

function title() {
  local result rpath
  rpath="$(grealpath --relative-base="${HOME}" "${PWD}")"

  if [ "${rpath:0:1}" = "/" ]; then
    result="${rpath}"
  elif [ "${rpath}" = "." ]; then
    result="${HOME}"
  else
    result="~/${rpath}"
  fi

  if [ "${#result}" -gt 30 ]; then
    result="$(last_parts "${result}")"
  fi

  echo -ne "\033]0;${result}\007"
}

autoload -U add-zsh-hook
add-zsh-hook precmd title
add-zsh-hook preexec title
