#!/usr/bin/env bash

function local-hook() {
  local hook="${PWD}/.git/hooks/$(basename $0)"

  if [[ -e "${hook}" ]]
  then
    ${hook}
    exit $?
  fi
}

function global-hook() {
  if [[ -x "bin/spring" ]]
  then
    echo "stopping spring"
    (bin/spring stop &>/dev/null) &
  fi

  echo "retagging"
  retag &
}

case ${PWD} in
  /usr/local/*|*Caches/Homebrew*)
    local-hook
    ;;
  *)
    global-hook
    local-hook
    ;;
esac
