#!/usr/bin/env bash

local_hook="${PWD}/.git/hooks/$(basename $0)"

if [[ -x "bin/spring" ]]
then
  echo "stopping spring"
  (bin/spring stop &>/dev/null) &
fi

echo "retagging"
retag &

if [[ -e "${local_hook}" ]]
then
  ${local_hook}
  exit $?
fi
