#!/usr/bin/env bash

if [[ "Darwin" == "$(uname)" ]]
then
  alias upgrade='brew update && brew upgrade'
  LS_COMMON="-G -h"
else
  LS_COMMON="--color=auto -th"
fi

export GREP_OPTIONS="--color=auto"

alias vi='vim'

alias ls="ls $LS_COMMON"
alias l='ls -A'
alias ll='ls -l'
alias la='ls -lA'

alias ..='cd ..'
alias ...='cd ../..'

alias h='history'

alias r='rails'
alias RD='RAILS_ENV=development'
alias RT='RAILS_ENV=test'
alias RP='RAILS_ENV=production'

alias v='vagrant'
alias vu='v up'
alias vus='vu && v ssh'
alias vh='v halt'
alias vr='v reload && vus'

alias g="git"
alias ga="g add -A"
alias gb="g b"
alias gbdall="git remote | xargs -n1 git remote prune"
alias gc="g c"
alias gclean="g clean"
alias gco="g co"
alias gd="g d"
alias gdc="gd --cached"
alias gdp="g dp"
alias gf="g f -p"
alias gfix="gc --amend --no-edit --reset-author"
alias gl="g l"
alias glp="g lp"
alias gm="g m"
alias gp="g pull"
alias gps="g push"
alias gr="g rebase"
alias grc="gr --continue"
alias grs="gr --skip"
alias gra="gr --abort"
alias gs="g s"
alias gstash="g stash"
alias gsub="git submodule"
alias gt="g tag"
alias gtl="gt --list --sort=version:refname"
alias gtoday="g today"
alias gtree="g tree"

alias psg="ps aux | grep -v grep | grep -i"

# Kills all the process with the given name.
function killer {
  kill -9 $(psg $@ | awk '{print $2}')
}

# Prints the ruby version and which architecture(32bits or 64bits) it was
# compiled.
rbv() {
  rbenv_ruby_version=`rbenv version-name`
  rbenv_ruby_arch=`ruby -e 'puts "#{[""].pack("p").size*8}bits"'`
  printf $rbenv_ruby_version"("$rbenv_ruby_arch")\n"
}
