#!/usr/bin/env bash

# Vim <3
alias v="vim"
n() { nvim $@ || vim $@ || vi $@ }

# System
alias ls="ls -G -h"
alias l="ls -l"
alias la="ls -lA"

alias ..="cd .."
alias ...="cd ../.."

alias sudo="A=`alias` sudo env "

alias brews="brew services"

# Searching
alias grep="grep --color=auto -i"

alias rg="rg --smart-case"
alias s="rg"

# Process
alias ctop="htop -s PERCENT_CPU"
alias mtop="htop -s PERCENT_MEM"

# Ruby and Rails
alias r="rails"
alias RD="RAILS_ENV=development"
alias RT="RAILS_ENV=test"
alias RS="RAILS_ENV=staging"
alias RP="RAILS_ENV=production"

alias DS="DISABLE_SPRING=1"

alias be="bundle exec"

# Git
alias g="git"
alias ga="g add -A"
alias gb="g b"
alias gbd="g b -d"
alias gbD="g b -D"
alias gbr="g b -r"
alias gc="g c"
alias gca="g ca"
alias gclean="g clean"
alias gco="g co"
alias gcom="gco master"
alias gcp="g cp"
alias gcpa="gcp --abort"
alias gcpc="gcp --continue"
alias gd="g d"
alias gdc="gd --cached"
alias gdp="g dp"
alias gf="g f -p"
alias gfix="g fix"
alias gl="g l"
alias glp="g lp"
alias glme="g lme"
alias glpme="g lpme"
alias gm="g m"
alias gma="g m --abort"
alias gp="g pull"
alias gps="g push"
alias gr="g r"
alias gra="g r --abort"
alias grc="g r --continue"
alias gri="g r -i"
alias grs="g r --skip"
alias gs="g s"
alias gt="g tag"
alias gtl="gt --list"
