#!/usr/bin/env bash

alias v='vim'
n() { nvim $@ || vim $@ || vi $@ }

alias ls="ls -G -h"
alias ll='ls -l'
alias la='ls -lA'

alias ..='cd ..'
alias ...='cd ../..'

alias sudo='A=`alias` sudo env '

alias brews='brew services'

alias r='rails'
alias RD='RAILS_ENV=development'
alias RT='RAILS_ENV=test'
alias RS='RAILS_ENV=staging'
alias RP='RAILS_ENV=production'

alias DS='DISABLE_SPRING=1'

alias be='bundle exec'

alias iexm='iex -S mix'

alias g="git"
alias ga="g add -A"
alias gb="g b"
alias gbd="g bd"
alias gbD="g bD"
alias gbr="g br"
alias gc="g c"
alias gca="g ca"
alias gclean="g clean"
alias gclone="g clone"
alias gco="g co"
alias gd="g d"
alias gdc="gd --cached"
alias gdp="g dp"
alias gf="g f -p"
alias gfix="g fix"
alias gl="g l"
alias glp="g lp"
alias glme="g lme"
alias glpme="g lpme"
alias gm="g m"
alias gma="g ma"
alias gp="g pull"
alias gps="g push"
alias gr="g r"
alias gra="g ra"
alias gremote="g remote"
alias grc="g rc"
alias gri="g ri"
alias grs="g rs"
alias greset="g reset"
alias gs="g s"
alias gstash="g stash"
alias gt="g tag"
alias gtl="gt --list --sort=version:refname"
alias gtoday="g today"
alias gtree="g tree"

alias ctop="htop -s PERCENT_CPU"
alias mtop="htop -s PERCENT_MEM"
