#!/usr/bin/env bash

# rbenv
if [ -d "$HOME/.rbenv" ]
then
  export PATH="$HOME/.rbenv/bin:/usr/local/sbin:$PATH"
  eval "$(rbenv init - --no-rehash)"
fi

### Added by the Heroku Toolbelt
_heroku_bin_path="/usr/local/heroku/bin"
if [[ -d $_heroku_bin_path ]]
then
  export PATH="$_heroku_bin_path:$PATH"
fi

# Default editor
export EDITOR='vim'

# Make ctrl-s works to incremental search, like ctrl-r to reverse
stty -ixon

# improve ls colors
export CLICOLOR=1

# Colorify less
export LESS_TERMCAP_mb=$(printf '\e[01;31m') # enter blinking mode - red
export LESS_TERMCAP_md=$(printf '\e[01;35m') # enter double-bright mode - bold, magenta
export LESS_TERMCAP_me=$(printf '\e[0m') # turn off all appearance modes (mb, md, so, us)
export LESS_TERMCAP_se=$(printf '\e[0m') # leave standout mode
export LESS_TERMCAP_so=$(printf '\e[01;33m') # enter standout mode - yellow
export LESS_TERMCAP_ue=$(printf '\e[0m') # leave underline mode
export LESS_TERMCAP_us=$(printf '\e[04;36m') # enter underline mode - cyan
export LESS=-r

# mysql prompt
export MYSQL_PS1='\d\$ '

# my lang
export LC_ALL="en_US.UTF-8"
export LC_CTYPE="en_US.UTF-8"
export LANG="en_US.UTF-8"

# git stuff for prompt
source $DOTFILES/lib/git-prompt.sh
export GIT_PS1_SHOWDIRTYSTATE=true
export GIT_PS1_SHOWSTASHSTATE=true
export GIT_PS1_SHOWUNTRACKEDFILES=true
export GIT_PS1_SHOWCOLORHINTS=true
export GIT_PS1_DESCRIBE_STYLE=branch
export GIT_PS1_SHOWUPSTREAM=verbose

export CDPATH=".:$HOME:$HOME/src"
export HOMEBREW_PREFIX="$(brew --prefix 2>/dev/null)"
export PATH="./bin:$PATH:$DOTFILES/bin"

source $DOTFILES/lib/aliases

# boxen-env
if [ -e /opt/boxen/env.sh ]
then
  source /opt/boxen/env.sh
fi

# local env
if [ -e "$HOME/.env" ]
then
  source $HOME/.env
fi
