#!/usr/bin/env bash

export __DEFINING_NOTIFY_TESTS=1

trim() {
  local var="$@"
  var="$(echo $var | sed -e 's/\s\{2,\}/\ /g')"
  var="${var#"${var%%[![:space:]]*}"}"   # remove leading whitespace characters
  var="${var%"${var##*[![:space:]]}"}"   # remove trailing whitespace characters
  echo -n "$var"
}

function __notify_tests_status {
  local last_status=$?
  local last_fc="$(fc -l -1)"
  local last_fc="$(trim $last_fc)"
  local last_command_id="$(echo $last_fc | cut -d' ' -f 1)"
  local last_command="$(echo $last_fc | cut -d' ' -f 2-)"

  if [ "$__LAST_COMMAND_ID" -eq "$last_command_id" -o -n "$__DEFINING_NOTIFY_TESTS" ]
  then
    unset __DEFINING_NOTIFY_TESTS
    return $last_status
  fi

  export __LAST_COMMAND_ID="$last_command_id"

  trap "{ return $last_status }" SIGINT

  function notifier {
    if [[ $(uname) == 'Darwin' ]]
    then
      `which terminal-notifier` -group 'TMUX' -message $1 &>/dev/null
    else
      `which notify-send` $1 &>/dev/null
    fi
  }

  case $last_command in
    *notify_tests_status*)
      ;;
    *spec*|*test*)
      if [ $last_status -eq 0 ]
      then
        notifier 'SUCCESS :)'
      else
        notifier 'FAILED :('
      fi
      ;;
  esac

  return $last_status
}
