#!/usr/bin/env bash

function notifier {
  if [[ $(uname) == 'Darwin' ]]
  then
    `which terminal-notifier` -group 'TMUX' -message $1 &>/dev/null
  else
    `which notify-send` $1 &>/dev/null
  fi
}

function __notify_tests_status {
  local last_status="$?"
  local last_fc="$(fc -l -1 | tr -s ' ')"
  local last_command_id="$(echo $last_fc | cut -d' ' -f 2)"
  local last_command="$(echo $last_fc | cut -d' ' -f 3-)"

  if [ "$__LAST_COMMAND_ID" -ne "$last_command_id" ]
  then
    export __LAST_COMMAND_ID="$last_command_id"
    trap "{ return $last_status }" SIGINT

    case $last_command in
      *notify_tests_status*)
        ;;
      *spec*|*test*)
        if [ $last_status -eq 0 ]
        then
          notifier 'SUCCESS :)'
        else
          notifier 'FAILED :('
        fi
        ;;
    esac
  fi

  return $last_status
}
