#!/usr/bin/env zsh

source "${HOMEBREW_PREFIX}/etc/bash_completion.d/git-prompt.sh"

export GIT_PS1_SHOWDIRTYSTATE=true
export GIT_PS1_SHOWSTASHSTATE=true
# export GIT_PS1_SHOWUNTRACKEDFILES=true
export GIT_PS1_SHOWUPSTREAM=true
export GIT_PS1_SHOWCOLORHINTS=true
export GIT_PS1_DESCRIBE_STYLE=branch
export GIT_PS1_SHOWUPSTREAM=verbose

 # To be overwritten on $HOME/.dotfiles.private/env
 __ps1_extra() { echo ''; }

 __ps1() {
   pre="%F{blue}%~%f"
   pos=$(echo -n "$(__ps1_extra)\n%(?.%F{green}.%F{red})$%f ")
   git="$(print -P " %F{yellow}(%f%%s%F{yellow})")"

   __git_ps1 ${pre} ${pos} ${git}
 }

precmd_functions+=__ps1
