#!/usr/bin/env zsh

DOTFILES="${HOME}/.dotfiles"

link() {
  file="$1"
  target="$2"
    if [ ! -L "${target}" ]; then
      echo "linking ${target}"
      ln -sf "${file}" "${target}"
    else
      echo "already linked ${target}"
    fi
}

link_dir() {
  while read file; do
    target_file="$(basename "${file}")"
    target="$(printf "$2" "${target_file}")"

    link "${file}" "${target}"
  done < <(find "$1" -d 1)
}

link_dir "${DOTFILES}/config/home" "${HOME}/.%s"
link_dir "${DOTFILES}/config/xdg" "${HOME}/.config/%s"

mkdir -p "${HOME}/.ssh"
link "${HOME}/config/ssh/config" "${HOME}/.ssh/config"

link_dir "${DOTFILES}/config/docker" "${HOME}/.docker"

link \
  "${DOTFILES}/config/iterm2scripts" \
  "${HOME}/Library/Application Support/iTerm2/Scripts"
