#!/usr/bin/env zsh

source_file="/tmp/nvim-macos.tar.gz"
install_path="${HOME}/src/nvim-nightly"
force=0

case "$1" in
  -f|--force)
    force=1
    shift
  ;;
esac

install() {
  rm -rf "${source_file}"
  rm -rf "${install_path}"

  curl \
    --url "https://github.com/neovim/neovim/releases/download/nightly/nvim-macos-arm64.tar.gz" \
    --output "${source_file}" \
    --progress-bar \
    --location

  xattr -c "${source_file}"
  pushd "${HOME}/src" &&
    tar xzf "${source_file}" &&
    mv "nvim-macos-arm64" "${install_path}"
  popd

  ln -sf "${install_path}/bin/nvim" "${HOMEBREW_PREFIX}/bin/nvim"

  nvim -V1 -v
}

if [ -f "${install_path}/bin/nvim" ]; then
  file_date="$(stat -t "%s" -f "%SB" "${install_path}/bin/nvim")"
  last_midnight="$(date -v "-$(date +"%H")H" +"%s")"
  if [ "${force}" -eq 0 ] && [ "${file_date}" -gt "${last_midnight}" ]; then
    echo "Already updated today"
    return
  fi
fi

echo "Installing nvim"
install
