#!/usr/bin/env zsh

softwareupdate -ia
xcode-select --install
sudo xcodebuild -license accept

basepath="$(dirname "$(realpath "$0")")"
scripts="${basepath}/macos"

# Disable Resume system-wide
defaults write com.apple.systempreferences NSQuitAlwaysKeepsWindows -int 0

# Automatically quit printer app once the print jobs complete
defaults write com.apple.print.PrintingPrefs "Quit When Finished" -bool true

for script in $(find "${scripts}" -type file -depth 1); do
  zsh "${script}"
done

# Kill affected applications
for app in Finder Dock SystemUIServer; do
  killall "${app}" > /dev/null 2>&1
done
