#!/usr/bin/env bash

# Fix PATH
if [ -x /usr/libexec/path_helper ]
then
  PATH=""
  eval `/usr/libexec/path_helper -s`
fi

export DOTFILES=$HOME/.dotfiles

source "$(brew --prefix)/etc/bash_completion"

function prompt_cmd {
  echo -ne "\e]1;${PWD/${HOME}/\$HOME}\a"
  local last_status=$?
  local blue='\[\e[0;34m\]'
  local red='\[\e[0;31m\]'
  local green='\[\e[0;32m\]'
  local reset='\[\e[00m\]'

  if [[ $last_status = 0 ]]
  then
    local prompt_color=$green
  else
    local prompt_color=$red
  fi

  __git_ps1 "$blue\w$reset" "
$prompt_color\$$reset "
}
PROMPT_COMMAND="prompt_cmd"

# Autocomplete
load_bash_completion() {
  local prefix=${HOMEBREW_PREFIX:-/usr/local}
  local brew_bash_completion="$prefix/etc/bash_completion"
  local brew_bash_completion_contributions="$prefix/Library/Contributions/brew_bash_completion.sh"

  [ -e "/etc/bash_completion" ] && source /etc/bash_completion
  [ -e $brew_bash_completion ] && source $brew_bash_completion
  [ -e $brew_bash_completion_contributions ] && source $brew_bash_completion_contributions
}; load_bash_completion

# Make ** works beautiful, works to any nested directory.
shopt -s globstar
# Enable dot files/folder on autocomplete
shopt -s dotglob

bind "set completion-ignore-case on"
bind "set show-all-if-ambiguous on"
complete -A hostname   rsh rcp telnet rlogin r ftp ping disk
complete -A export     printenv
complete -A variable   export local readonly unset
complete -A enabled    builtin
complete -A alias      alias unalias
complete -A function   function
complete -A user       su mail finger
complete -o default -o nospace -F _rakecomplete rake
complete -o default -o nospace -F _capcomplete cap
complete -o default -o nospace -F _thorcomplete thor

# Append user history
shopt -s histappend

# History
export HISTCONTROL=$HISTCONTROL${HISTCONTROL+,}ignoredups
export HISTCONTROL=ignoreboth
export HISTFILESIZE=10000000000
export HISTSIZE=1000000

# Make ctrl-s works to incremental search, like ctrl-r to reverse
stty -ixon

# Load zsh
fzf_path="${HOMEBREW_PREFIX}/opt/fzf"
if [ -d "${fzf_path}" ]
then
  source "${fzf_path}/shell/completion.bash"
  source "${fzf_path}/shell/key-bindings.bash"
fi

# My env customization (this line must be the very last on this file)
source "$DOTFILES/lib/env"
