#!/usr/bin/env bash
# Reference https://www.rightpoint.com/rplabs/script-keyboard-os-x-shortcuts

function addCustomMenuEntryIfNeeded {
  local CUSTOM="com.apple.custommenu.apps"
  if [[ $# == 0 || $# > 1 ]]; then
    echo "usage: addCustomMenuEntryIfNeeded com.company.appname"
    return 1
  else
    local contents=$(defaults read com.apple.universalaccess "${CUSTOM}")
    local grepResults=$(echo $contents | grep $1)

    if [[ -z $grepResults ]]; then
      # does not contain app
      sudo defaults write com.apple.universalaccess "${CUSTOM}" -array-add "$1"
    fi
  fi
}


CMD='@'
OPTION='~'
CTRL='^'
SHIFT='$'

# Global
defaults write NSGlobalDomain NSUserKeyEquivalents "{
  \"Merge All Windows\" = \"${CMD}${OPTION}${CTRL}m\";
}"

# Safari
defaults write "com.apple.Safari"  NSUserKeyEquivalents "{
  \"Email This Page\" = \"${CMD}${OPTION}${CTRL}${SHIFT}8\";
  \"Quit Safari\" = \"${CMD}${OPTION}q\";
}"
addCustomMenuEntryIfNeeded "com.apple.Safari"

# Notes
defaults write "com.apple.Notes" NSUserKeyEquivalents "{
    \"Hide Folders\" = \"${CMD}${SHIFT}s\";
    \"Show Folders\" = \"${CMD}${SHIFT}s\";
}"
addCustomMenuEntryIfNeeded "com.apple.Notes"

# Preview
defaults write "com.apple.Preview" NSUserKeyEquivalents "{
  \"Adjust Size...\" = \"${CMD}${OPTION}${CTRL}i\";
}"
addCustomMenuEntryIfNeeded "com.apple.Preview"

# Force global keyboard config to follow the 'local'
sudo cp ~/Library/Preferences/com.apple.HIToolbox.plist \
  /Library/Preferences/com.apple.HIToolbox.plist

sudo killall cfprefsd
sudo killall Finder
