require('globals') -- global functions (used for debbuging)
require('extensions') -- lua extensions (used everywhere)

-- my own set of configs and helpers (plugin independent)
require('my.options')
require('my.keymaps')
require('my.commands')
require('my.diagnostic')

-- plugins configurations
require('plugins').setup()
require('plugins.icons')
require('plugins.highlight')
require('plugins.comment')
require('plugins.projection')
require('plugins.notification')
require('plugins.git')
require('plugins.filetree')
require('plugins.terminal-handler')
require('plugins.test-runner')
require('plugins.fuzzyfinder')
require('plugins.treesitter')
require('plugins.completion')
require('plugins.lsp')
require('plugins.debugger')
require('plugins.todo')
require('plugins.aligner')
require('plugins.surround')
require('plugins.session')
require('plugins.statusline')
require('plugins.tabline')
require('plugins.winbar')
require('plugins.focus')
require('plugins.lists')
