#!/usr/bin/env bash

# Install Homebrew
/usr/bin/ruby -e \
  "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

# Install the basic
brew bundle --file="${INSTALLER}/Brewfile"

# Setup default gems
ln -sf ${INSTALLER}/default-gems ${HOME}/.rbenv/default-gems
