#!/usr/bin/env bash

# Install Homebrew
/usr/bin/ruby -e \
  "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
hombrew_prefix=${HOMEBREW_PREFIX:-/usr/local}

# Customize my paths
cat /etc/paths | sudo tee /etc/paths.d/system
echo "" | sudo tee /etc/paths
echo "${homebrew_prefix}/bin" | sudo tee /etc/paths.d/homebrew
echo "${homebrew_prefix}/sbin" | sudo tee -a /etc/paths.d/homebrew

# reset $PATH
eval $(/usr/libexec/path_helper -s)

# Install the basic
brew bundle --file="${INSTALLER}/Brewfile"

# Setup default gems
ln -sf ${INSTALLER}/default-gems ${HOME}/.rbenv/default-gems

# Make custom shells available
[[ $(grep "${homebrew_prefix}/bin/bash" /etc/shells) ]] || \
  echo "${homebrew_prefix}/bin/bash" | sudo tee -a /etc/shells
[[ $(grep "${homebrew_prefix}/bin/zsh" /etc/shells) ]] || \
  echo "${homebrew_prefix}/bin/zsh" | sudo tee -a /etc/shells
