#!/usr/bin/env bash

# Create linked files
for f in $HOME/.dotfiles/symlink/*
do
  ln -sf $f $HOME/.${f##*/}
done

# Copy docker config to the right place
mkdir -p $HOME/.docker
ln -sf $HOME/.dotfiles/lib/docker_config.json $HOME/.docker/config.json
