#!/usr/bin/env bash

source "$(dirname $0)/global"

# Disable the sound effects on boot
sudo nvram SystemAudioVolume=" "

# Disable Resume system-wide
defaults write com.apple.systempreferences NSQuitAlwaysKeepsWindows -int 0

for s in ${INSTALLER}/macos/*
do
  exec $s
done


# Kill affected applications
for app in Finder Dock SystemUIServer
do
  killall "$app" >/dev/null 2>&1
done

# Doesn't work on El captain:
# sudo chflags -h nohidden /tmp
