#!/usr/bin/env bash

RBENV_PATH="$HOME/.rbenv"
if [ ! -e $RBENV_PATH ]
then
  old_path=$PWD

  git clone https://github.com/rbenv/rbenv.git $RBENV_PATH
  cd $RBENV_PATH && src/configure && make -C src
  git clone https://github.com/rbenv/ruby-build.git $RBENV_PATH/plugins/ruby-build

  cd $PWD
fi
