#!/usr/bin/env bash


# Create linked files
for f in ${HOME}/.dotfiles/symlink/*
do
  ln -sf ${f} ${HOME}/.${f##*/}
done

docker_dir="${HOME}/.docker"
mkdir -p ${docker_dir}
ln -sf ${HOME}/.dotfiles/install/docker/config.json ${docker_dir}/config.json

ydl_dir="${HOME}/.config/youtube-dl"
mkdir -p ${ydl_dir}
ln -sf ${HOME}/.dotfiles/install/config/youtube-dl/config ${ydl_dir}/config
