#!/usr/bin/env bash

source "$(dirname $0)/global"

# Create linked files
for f in ${INSTALLER}/rcfiles/home/*
do
  ln -sf ${f} ${HOME}/.${f##*/}
done

mkdir -p ${HOME}/.config
for f in ${INSTALLER}/rcfiles/home-config/*
do
  ln -sf ${f} ${HOME}/.config/${f##*/}
done

mkdir -p ${HOME}/.atom
for f in ${INSTALLER}/rcfiles/atom/*
do
  ln -sf ${f} ${HOME}/.atom/${f##*/}
done

# ssh
# These configs needs to be copied because they are completed for Zendesk
# softwares.
mkdir -p ${HOME}/.ssh
cp ${INSTALLER}/ssh_config ${HOME}/.ssh/config
chmod -R 700 ${HOME}/.ssh
