#!/usr/bin/env bash

source "$(dirname $0)/global"

# Ask for superpowers upfront
sudo -v

pushd ${HOME} > /dev/null && trap 'popd > /dev/null' EXIT HUP INT QUIT TERM

${INSTALLER}/setup-xcode
${INSTALLER}/setup-basic-packages
${INSTALLER}/setup-shell
${INSTALLER}/setup-rcfiles
${INSTALLER}/setup-vscode
${INSTALLER}/setup-asdf
${INSTALLER}/setup-backspace
source ${DOTFILES}/lib/env

# Installing all my stuff
title "Install all the brews"
brew bundle --global

# install iterm2 integration
title "Install the iterm2 integrations"
update-iterm2-integrations

# Customize installed tools
${INSTALLER}/setup-macos
${INSTALLER}/setup-sudo-fingerprint
${INSTALLER}/setup-gpg

if [ -f ${HOME}/Dropbox/dotfiles/custom-setup ]
then
  ${HOME}/Dropbox/dotfiles/custom-setup
fi

exit 0
