#!/usr/bin/env bash

title "Setup MacOS configurations"

source "$(dirname $0)/global"
macos_path="${INSTALLER}/macos"

# Disable the sound effects on boot
sudo nvram SystemAudioVolume=" "

# Disable Resume system-wide
defaults write com.apple.systempreferences NSQuitAlwaysKeepsWindows -int 0

for script in $(find ${macos_path} -type f -d 1)
do
  bash ${script}
done

${macos_path}/services/install

# Kill affected applications
for app in Finder Dock SystemUIServer
do
  killall "$app" >/dev/null 2>&1
done
