#!/usr/bin/env bash

title "Setup ruby"

source "$(dirname $0)/global"

# Setup default gems
ln -sf ${INSTALLER}/default-gems ${HOME}/.rbenv/default-gems

RUBY_VERSION="$(rbenv install -l | grep "^\s*\d\.\d\.\d$" | tail -1 | tr -d ' ')"

rbenv install --skip-existing ${RUBY_VERSION}
rbenv global ${RUBY_VERSION}
