#!/usr/bin/env bash

source "$(dirname $0)/global"
macos_path="${INSTALLER}/macos"

# Disable the sound effects on boot
sudo nvram SystemAudioVolume=" "

# Disable Resume system-wide
defaults write com.apple.systempreferences NSQuitAlwaysKeepsWindows -int 0

for s in $(ls -1 ${macos_path})
do
  bash ${macos_path}/$s
done

# Kill affected applications
for app in Finder Dock SystemUIServer
do
  killall "$app" >/dev/null 2>&1
done

# Enable fingerprint with sudo
replacement='2i \
auth       sufficient     pam_tid.so\
'
sudo mv /etc/pam.d/sudo{,.original}
sed -e "${replacement}" /etc/pam.d/sudo.original | sudo tee /etc/pam.d/sudo

# Doesn't work on El captain:
# sudo chflags -h nohidden /tmp
