#!/usr/bin/env bash

old_path="$PWD"
cd $HOME
RUBY_VERSION="2.3.1"

# Prepare my dev folder
mkdir -p $HOME/src

# Install Homebrew
/usr/bin/ruby -e \
  "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

# Customize my paths
if [ -z "$(ag "$HOMEBREW_PREFIX" /etc/paths)" ]
then
  echo "$HOMEBREW_PREFIX/bin" | sudo tee -a /etc/paths
  echo "$HOMEBREW_PREFIX/sbin" | sudo tee -a /etc/paths
fi

# Install all my packages
brew bundle --global

# Init postgres
brew services start --all
init-pg

# Create linked files
for f in $HOME/.dotfiles/symlink/*
do
  ln -sf $f $HOME/.${f##*/}
done

# Load some of my env
source $HOME/.dotfiles/lib/env

# Install ruby
rbenv install $RUBY_VERSION
rbenv global $RUBY_VERSION

# Install linters
update-linters

# Setup customized shells
if [ -z "$(ag "$HOMEBREW_PREFIX" /etc/shells)" ]
then
  echo $(type -p zsh) | sudo tee -a /etc/shells
  echo $(type -p bash) | sudo tee -a /etc/shells
fi

# Change my shell to zsh
chsh -s $(type -p zsh)

# Customize OSX
$HOME/.dotfiles/install/osx

echo 'Restart the shell! :)'

cd $old_path
