#!/usr/bin/env zsh

export DOTFILES=${HOME}/.dotfiles
export HOMEBREW_PREFIX=${HOMEBREW_PREFIX:-/usr/local}

# Fix PATH
if [ -x /usr/libexec/path_helper ]
then
  PATH=""
  eval `/usr/libexec/path_helper -s`
fi

autoload -Uz compinit
compinit -C
autoload bashcompinit
bashcompinit

autoload -U colors && colors

## Binds
# Use emacs key bindings
bindkey -e

# Del
bindkey '\e[3~'   delete-char
# Ctrl+u deletes from cursor position to line beginning
bindkey \^U       backward-kill-line

# c-x c-e edit command line in ${EDITOR}
autoload -U edit-command-line
zle -N edit-command-line
bindkey '\C-x\C-e' edit-command-line

# Fix the \eb \ef and others.
export WORDCHARS=''

# colors on autocomplete
zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}

# case-insensitive (all),partial-word and then substring completion
zstyle ':completion:*' matcher-list \
  'm:{a-zA-Z}={A-Za-z}' \
  'r:|[._-]=* r:|=*' 'l:|=* r:|=*'

unsetopt MENU_COMPLETE   # do not autoselect the first completion entry
unsetopt FLOWCONTROL
setopt AUTO_MENU         # show completion menu on succesive tab press
setopt COMPLETE_IN_WORD
setopt ALWAYS_TO_END
skip_global_compinit=1

for key in '!' '$' '@' '/'; do
  bindkey "\e${key}" _bash_complete-word
  bindkey "^X${key}" _bash_list-choices
done

# do not correct me!!
unsetopt CORRECT_ALL
unsetopt CORRECT

# Do not show % on partial lines ends
setopt PROMPT_CR
setopt PROMPT_SP
export PROMPT_EOL_MARK=""

## History
export HISTFILE=${HOME}/.zhistory
export HISTSIZE=120000
export SAVEHIST=100000
setopt BANG_HIST                 # Treat the '!' character specially during expansion.
setopt INC_APPEND_HISTORY        # Write to the history file immediately, not when the shell exits.
setopt SHARE_HISTORY             # Share history between all sessions.
setopt HIST_SAVE_NO_DUPS         # Don't write duplicate entries in the history file.
setopt HIST_FIND_NO_DUPS         # Do not display a line previously found.
setopt HIST_IGNORE_ALL_DUPS      # Delete old recorded entry if new entry is a duplicate.
setopt HIST_IGNORE_DUPS          # Don't record an entry that was just recorded again.
setopt HIST_EXPIRE_DUPS_FIRST    # Expire duplicate entries first when trimming history.
setopt HIST_REDUCE_BLANKS        # Remove superfluous blanks before recording entry.
setopt HIST_VERIFY               # Don't execute immediately upon history expansion.
setopt HIST_NO_STORE             # Don't save history command on history
unsetopt HIST_IGNORE_SPACE       # Ignore space prefixed commands
unsetopt EXTENDED_HISTORY

## Extra
# easy regexp on list files (**)
setopt EXTENDEDGLOB
# include dotfiles in globbing
setopt GLOB_DOTS
# don't blow up with comments
setopt INTERACTIVE_COMMENTS

## Completions
fpath=(/usr/local/share/zsh-completions ${fpath})

function __ps1() {
  if [ "$?" -eq 0 ]
  then
    local prompt_color="%F{green}"
  else
    local prompt_color="%F{red}"
  fi

  local part1="%F{blue}%~%f"
  local part2="
${prompt_color}$%f "
  local part3="$(print -P " %F{yellow}(%f%%s%F{yellow})")"

  __git_ps1 ${part1} ${part2} ${part3}
}

brew_completion="${HOMEBREW_PREFIX}/Library/Contributions/brew_zsh_completion.sh"
if [[ -e ${brew_completion} ]]
then
  source ${brew_completion}
fi

# My env customization (this line must be the very last on this file)
source "${DOTFILES}/lib/env"

# Libraries loading

fzf_path="${HOMEBREW_PREFIX}/opt/fzf"
if [ -d "${fzf_path}" ]
then
  source "${fzf_path}/shell/completion.zsh"
  source "${fzf_path}/shell/key-bindings.zsh"
fi

source "${HOMEBREW_PREFIX}/etc/bash_completion.d/git-prompt.sh"
source "${HOMEBREW_PREFIX}/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"
source "${HOMEBREW_PREFIX}/share/zsh-autosuggestions/zsh-autosuggestions.zsh"
