local servers_map = require('mason-lspconfig.mappings.server').package_to_lspconfig

return table.slice(servers_map, {
  'bash-language-server',
  'css-lsp',
  'dockerfile-language-server',
  'editorconfig-checker',
  'go-debug-adapter',
  'golangci-lint',
  'golangci-lint-langserver',
  'golines',
  'gopls',
  'gotests',
  'graphql-language-service-cli',
  'html-lsp',
  'json-lsp',
  'jsonnet-language-server',
  'lua-language-server',
  'luacheck',
  'luaformatter',
  'markdownlint',
  'prettier',
  'shellcheck',
  'shfmt',
  'solargraph',
  'sql-formatter',
  'sqlls',
  'sqls',
  'stylua',
  'tailwindcss-language-server',
  'typescript-language-server',
  'vetur-vls',
  'vim-language-server',
  'vint',
  'vue-language-server',
  'yaml-language-server',
  'yamllint',
})
